//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NEO_Quiz.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć członka, edytuj plik .ResX, a następnie ponownie uruchom ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NEO_Quiz.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lorem ipsum dolor sit amet.
        /// </summary>
        public static string AnswerPlaceholder {
            get {
                return ResourceManager.GetString("AnswerPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozpocznij.
        /// </summary>
        public static string BeginButton {
            get {
                return ResourceManager.GetString("BeginButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Anuluj quiz.
        /// </summary>
        public static string CancelQuizButton {
            get {
                return ResourceManager.GetString("CancelQuizButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czy napewno chcesz zakończyć quiz?.
        /// </summary>
        public static string CancelQuizNotice {
            get {
                return ResourceManager.GetString("CancelQuizNotice", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zatwierdź odpowiedź.
        /// </summary>
        public static string CheckAnswerButon {
            get {
                return ResourceManager.GetString("CheckAnswerButon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zamknij.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prawidłowe odpowiedzi:.
        /// </summary>
        public static string CorrectAnswersLabel {
            get {
                return ResourceManager.GetString("CorrectAnswersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Następne pytanie.
        /// </summary>
        public static string NextQuestionButton {
            get {
                return ResourceManager.GetString("NextQuestionButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie.
        /// </summary>
        public static string NoButton {
            get {
                return ResourceManager.GetString("NoButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Maksimum pytań.
        /// </summary>
        public static string QUESTION_MAX {
            get {
                return ResourceManager.GetString("QUESTION_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minimum pytań.
        /// </summary>
        public static string QUESTION_MIN {
            get {
                return ResourceManager.GetString("QUESTION_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pytanie:.
        /// </summary>
        public static string QuestionInfoLabel {
            get {
                return ResourceManager.GetString("QuestionInfoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus sem odio, ut vehicula velit laoreet fringilla. Donec varius nibh vitae pretium ultrices. Maecenas dolor enim, dignissim eget efficitur eget, cursus eu dui. Praesent vestibulum dui pretium dui imperdiet sodales. Mauris volutpat, diam vitae porta rutrum, urna ante placerat justo, et congue risus metus at tellus. Maecenas sodales arcu ac nibh ullamcorper scelerisque. Interdum et malesuada fames ac ante ipsum primis in faucibus. Fusce fa [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        public static string QuestionPlaceHolder {
            get {
                return ResourceManager.GetString("QuestionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba pytań:.
        /// </summary>
        public static string QuestionsCountLabel {
            get {
                return ResourceManager.GetString("QuestionsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tym razem się nie udało. Spróbuj ponownie!.
        /// </summary>
        public static string QuizLoseInfo {
            get {
                return ResourceManager.GetString("QuizLoseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tryb quizu:.
        /// </summary>
        public static string QuizModeLabel {
            get {
                return ResourceManager.GetString("QuizModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprawnych odpowiedzi:.
        /// </summary>
        public static string QuizWonAnswerCorrect {
            get {
                return ResourceManager.GetString("QuizWonAnswerCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gratulujemy wygranej!.
        /// </summary>
        public static string QuizWonInfo {
            get {
                return ResourceManager.GetString("QuizWonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Liczba poprawnych odpowiedzi: {0}.
        /// </summary>
        public static string QuizWonMaxModeInfoContent {
            get {
                return ResourceManager.GetString("QuizWonMaxModeInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozwiązałeś quiz!.
        /// </summary>
        public static string QuizWonMaxModeInfoHeader {
            get {
                return ResourceManager.GetString("QuizWonMaxModeInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Poprawnych odpowiedzi {0}. Wyświetlono pytań {1}. .
        /// </summary>
        public static string QuizWonMinModeInfoContent {
            get {
                return ResourceManager.GetString("QuizWonMinModeInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Rozwiązałeś quiz!.
        /// </summary>
        public static string QuizWonMinModeInfoHeader {
            get {
                return ResourceManager.GetString("QuizWonMinModeInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Odpowiedziałeś poprawnie na {0} pytań..
        /// </summary>
        public static string QuizWonTimeEndInfoContent {
            get {
                return ResourceManager.GetString("QuizWonTimeEndInfoContent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Koniec czasu!.
        /// </summary>
        public static string QuizWonTimeEndInfoHeader {
            get {
                return ResourceManager.GetString("QuizWonTimeEndInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Twój czas:.
        /// </summary>
        public static string QuizWonTimeInfo {
            get {
                return ResourceManager.GetString("QuizWonTimeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gratulujemy. Odpowiedziałeś na wszystkie pytania..
        /// </summary>
        public static string QuizWonTimeQuestonEndInfoHeader {
            get {
                return ResourceManager.GetString("QuizWonTimeQuestonEndInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisz zmiany.
        /// </summary>
        public static string SaveChangesButton {
            get {
                return ResourceManager.GetString("SaveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ustawienia.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pozostały czas:.
        /// </summary>
        public static string TimeLeftLabel {
            get {
                return ResourceManager.GetString("TimeLeftLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Limit czasu:.
        /// </summary>
        public static string TimeLimitLabel {
            get {
                return ResourceManager.GetString("TimeLimitLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Limit czasowy.
        /// </summary>
        public static string TIMEOUT {
            get {
                return ResourceManager.GetString("TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tak.
        /// </summary>
        public static string YesButton {
            get {
                return ResourceManager.GetString("YesButton", resourceCulture);
            }
        }
    }
}
